# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
host: 0.0.0.0
url: http://localhost:8000

blog:
  tags:
    dir: "blog/tags/"
    layout: "tag.html"
    title_prefix: "Website Title / Blog / Tags / "
  category:
    dir: "blog/categories/"
    layout: "category.html"
    title_prefix: "Website Title / Blog / Categories / "

categories_list: [
  'General'
]
tags_list: [
  'General',
  'Introduction'
]

prose:
  rooturl: "source"
  siteuril: "http://localhost:8000"
  metadata: true

title: Website Title
email: website@template.com
name: Website Name
description: Website description goes here.
source: source
destination: site
baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "http://example.com" # the base hostname & protocol for your site
twitter_username:
github_username:

subscribe_rss: /atom.xml

permalink: /:categories/:title/
excerpt_separator: <!-- more -->

# Build settings
markdown: kramdown

sass:
  style: :compressed
